<?php

namespace ArchBundle\Repository;

/**
 * BattleUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattleUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
