<?php

namespace ArchBundle\Repository;

/**
 * BattleLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattleLogRepository extends \Doctrine\ORM\EntityRepository
{
}
