<?php

namespace ArchBundle\Repository;

/**
 * BattleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattleRepository extends \Doctrine\ORM\EntityRepository
{
}
