<?php

namespace ArchBundle\Repository;

/**
 * ResourceNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceNameRepository extends \Doctrine\ORM\EntityRepository
{
}
