<?php

namespace ArchBundle\Repository;

/**
 * StructureNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StructureNameRepository extends \Doctrine\ORM\EntityRepository
{
}
