<?php

namespace ArchBundle\Repository;

/**
 * StructureCostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StructureCostRepository extends \Doctrine\ORM\EntityRepository
{
}
