<?php

namespace ArchBundle\Repository;

/**
 * StructureUpgradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StructureUpgradeRepository extends \Doctrine\ORM\EntityRepository
{
}
