<?php

namespace ArchBundle\Repository;

/**
 * UnitNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitNameRepository extends \Doctrine\ORM\EntityRepository
{
}
