<?php

namespace ArchBundle\Repository;

/**
 * UnitCostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitCostRepository extends \Doctrine\ORM\EntityRepository
{
}
