<?php

namespace ArchBundle\Repository;

/**
 * UnitStructureDependencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitStructureDependencyRepository extends \Doctrine\ORM\EntityRepository
{
}
