<?php

namespace ArchBundle\Repository;

/**
 * UnitProductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitProductionRepository extends \Doctrine\ORM\EntityRepository
{
}
